// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelChat(requestID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2522773405, requestID);
}

export function CreateConversation(): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(1021935206);
}

export function ListConversations(): $CancellablePromise<$models.ConversationSummary[] | null> {
    return $Call.ByID(1664713955);
}

export function ListModels(profile: $models.ConnectionProfile): $CancellablePromise<$models.Model[] | null> {
    return $Call.ByID(919729239, profile);
}

export function OpenConversation(id: string): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(3465756378, id);
}

export function SaveConversation(conversation: $models.Conversation): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(3192203735, conversation);
}

export function StartChat(request: $models.ChatRequest): $CancellablePromise<void> {
    return $Call.ByID(1745474569, request);
}
