// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatEvent {
    "requestID": string;
    "type": string;
    "delta"?: string;
    "error"?: string;
}

export interface ChatMessage {
    "role": string;
    "content": string;
}

export interface ChatRequest {
    "requestID": string;
    "profile": ConnectionProfile;
    "model": string;
    "messages": ChatMessage[] | null;
}

export interface ConnectionProfile {
    "baseURL": string;
    "apiKey": string;
}

export interface Model {
    "id": string;
    "ownedBy"?: string;
}
