// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatEvent {
    "requestID": string;
    "type": string;
    "delta"?: string;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
    "error"?: string;
}

export interface ChatMessage {
    "role": string;
    "content": string;
}

export interface ChatRequest {
    "requestID": string;
    "profile": ConnectionProfile;
    "model": string;
    "messages": ChatMessage[] | null;
}

export interface ConnectionProfile {
    "baseURL": string;
    "apiKey": string;
}

export interface Conversation {
    "id": string;
    "title": string;
    "createdAt": string;
    "updatedAt": string;
    "messages": ConversationMessage[] | null;
}

export interface ConversationMessage {
    "id": string;
    "role": string;
    "content": string;
    "status": string;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
}

export interface ConversationSummary {
    "id": string;
    "title": string;
    "updatedAt": string;
    "messageCount": number;
}

export interface Model {
    "id": string;
    "ownedBy"?: string;
}

/**
 * ResponseMetrics is measured locally for each streaming response. The first
 * token duration is zero when a server finishes without emitting text.
 */
export interface ResponseMetrics {
    "totalDurationMs": number;
    "firstTokenDurationMs": number;
}

/**
 * SavedConnectionProfile deliberately excludes the API key and model. The API
 * key exists only in memory, and models are fetched again when a user connects.
 */
export interface SavedConnectionProfile {
    "id": string;
    "name": string;
    "baseURL": string;
}

/**
 * TokenUsage is the token accounting reported by a compatible chat server for
 * one completed request. Prompt and completion tokens are kept separately so
 * the frontend can present total token usage without estimating tokens from
 * text.
 */
export interface TokenUsage {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
}
