// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatEvent {
    "requestID": string;
    "type": string;
    "delta"?: string;
    "error"?: string;
}

export interface ChatMessage {
    "role": string;
    "content": string;
}

export interface ChatRequest {
    "requestID": string;
    "profile": ConnectionProfile;
    "model": string;
    "messages": ChatMessage[] | null;
}

export interface ConnectionProfile {
    "baseURL": string;
    "apiKey": string;
}

export interface Conversation {
    "id": string;
    "title": string;
    "createdAt": string;
    "updatedAt": string;
    "messages": ConversationMessage[] | null;
}

export interface ConversationMessage {
    "id": string;
    "role": string;
    "content": string;
    "status": string;
}

export interface ConversationSummary {
    "id": string;
    "title": string;
    "updatedAt": string;
    "messageCount": number;
}

export interface Model {
    "id": string;
    "ownedBy"?: string;
}

/**
 * SavedConnectionProfile deliberately contains only the server URL. Models are
 * fetched from that server when the user chooses to load them, and API keys
 * remain in memory only.
 */
export interface SavedConnectionProfile {
    "baseURL": string;
}
